2022-12-06 06:54:41,700 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 06:54:41,804 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 06:54:44,517 |    INFO | server | Connection from ('127.0.0.1', 51464) | waiting authorize
2022-12-06 06:54:58,455 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 256 | 
2022-12-06 06:54:58,462 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-06 06:55:05,100 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670298905.098142, 'user': {'password': 'pass', 'username': 'user_1'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-06 06:55:05,102 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 164 | 
2022-12-06 06:55:05,105 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-06 06:55:32,667 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'action': 3, 'from': 'user_1', 'message': 'hi', 'time': 1670298932.664887, 'to': 'user_1'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 96 | 
2022-12-06 06:55:49,304 |    INFO | server | fnc: generate_response_message | args: (<Status.NotFound: 404>,) | kwargs: {'error': 'User is not logged in'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 100 | 
2022-12-06 06:55:59,319 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'action': 3, 'from': 'user_1', 'message': 'quit!', 'time': 1670298959.317505, 'to': 'user_1'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 96 | 
2022-12-06 06:56:02,070 |    INFO | server | Client ('127.0.0.1', 51464) wants to quit
2022-12-06 06:56:02,323 |    INFO | server | User "user_1" disconnected
2022-12-06 06:56:02,323 |   ERROR | server | Server error | user_1 ('127.0.0.1', 51464) has already left
2022-12-06 06:56:12,442 |    INFO | server | Connection from ('127.0.0.1', 51514) | waiting authorize
2022-12-06 06:56:17,445 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670298977.443944, 'user': {'password': 'pass', 'username': 'user_1'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-06 06:56:17,447 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 164 | 
2022-12-06 06:56:17,450 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-06 06:56:22,681 |    INFO | server | Client ('127.0.0.1', 51514) wants to quit
2022-12-06 06:56:22,943 |    INFO | server | User "user_1" disconnected
2022-12-06 06:56:22,943 |   ERROR | server | Server error | user_1 ('127.0.0.1', 51514) has already left
2022-12-06 06:59:02,186 | WARNING | server | Server closing
2022-12-06 06:59:04,864 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 06:59:04,906 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 07:36:48,115 | WARNING | server | Server closing
2022-12-06 07:36:50,158 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 07:36:50,200 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 07:37:04,785 | WARNING | server | Server closing
2022-12-06 07:37:05,941 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 07:37:05,982 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 07:37:09,642 |    INFO | server | Connection from ('127.0.0.1', 52877) | waiting authorize
2022-12-06 07:37:17,773 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 256 | 
2022-12-06 07:37:17,779 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-06 07:37:22,340 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670301442.338171, 'user': {'password': 'pass', 'username': 'user_1'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-06 07:37:22,341 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 156 | 
2022-12-06 07:37:22,344 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-06 07:39:36,106 | WARNING | server | Server closing
2022-12-06 07:39:38,093 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 07:39:38,134 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 07:40:09,572 | WARNING | server | Server closing
2022-12-06 07:41:42,777 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 07:41:42,818 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 07:41:45,425 |    INFO | server | Connection from ('127.0.0.1', 53078) | waiting authorize
2022-12-06 07:41:54,976 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 258 | 
2022-12-06 07:41:54,983 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 62 | 
2022-12-06 07:42:00,059 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670301720.057743, 'user': {'password': 'pass', 'username': 'user_1'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-06 07:42:00,061 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 157 | 
2022-12-06 07:42:00,064 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 73 | 
2022-12-06 07:42:17,298 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'action': 3, 'from': 'user_1', 'message': 'pass', 'time': 1670301737.296957, 'to': 'user_1'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 89 | 
2022-12-06 07:42:26,876 |    INFO | server | Client ('127.0.0.1', 53078) wants to quit
2022-12-06 07:42:27,138 |    INFO | server | User "user_1" disconnected
2022-12-06 07:42:27,138 |   ERROR | server | Server error | user_1 ('127.0.0.1', 53078) has already left
2022-12-06 07:51:17,630 | WARNING | server | Server closing
2022-12-06 07:51:20,498 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-06 07:51:20,540 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-06 07:51:23,190 |    INFO | server | Connection from ('127.0.0.1', 53450) | waiting authorize
2022-12-06 07:51:31,425 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 260 | 
2022-12-06 07:51:31,431 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 62 | 
2022-12-06 07:51:36,614 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670302296.612736, 'user': {'password': 'pass', 'username': 'user_1'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-06 07:51:36,616 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 158 | 
2022-12-06 07:51:36,619 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 73 | 
2022-12-06 07:51:40,630 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'action': 3, 'from': 'user_1', 'message': 'pass', 'time': 1670302300.628872, 'to': 'user_1'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 89 | 
2022-12-06 07:52:04,302 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'action': 3, 'from': 'user_1', 'message': "This is a test message, dont answer it'' please", 'time': 1670302324.3004, 'to': 'user_1'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 89 | 
2022-12-06 07:52:40,362 |    INFO | server | Connection from ('127.0.0.1', 53513) | waiting authorize
2022-12-06 07:52:47,269 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 260 | 
2022-12-06 07:52:47,276 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 62 | 
2022-12-06 07:52:53,069 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670302373.06793, 'user': {'password': 'pass', 'username': 'user_2'}}, {'user_1': <StreamWriter transport=<_ProactorSocketTransport fd=440 read=<_OverlappedFuture pending overlapped=<pending, 0x2246fa624c0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002246FA74700>()]> transport=<_ProactorSocketTransport fd=440 read=<_OverlappedFuture pending overlapped=<pending, 0x2246fa624c0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-06 07:52:53,070 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 158 | 
2022-12-06 07:52:53,074 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 73 | 
2022-12-06 07:52:57,324 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'action': 3, 'from': 'user_2', 'message': 'Hello friend', 'time': 1670302377.322961, 'to': 'user_1'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 89 | 
2022-12-06 07:53:28,387 | WARNING | server | Server closing
