2022-11-30 11:43:15,572 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,577 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:43:15,581 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,584 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,590 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,593 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,598 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,603 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,606 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,609 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function test_password_hashing_is_correct line 50 | 
2022-11-30 11:43:15,612 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,615 |    INFO | server | fnc: is_authorized | args: ({'user': {'username': 'u2', 'password': 'password'}}, {'u2': 'StreamWriter', 'user1': 'StreamWriter'}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function test_user_is_authorized line 74 | 
2022-11-30 11:43:15,615 |    INFO | server | User is already authorized
authorized = {'u2': 'StreamWriter', 'user1': 'StreamWriter'}
2022-11-30 11:43:15,619 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,623 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:48:16,456 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 11:48:16,460 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 11:48:22,900 |    INFO | server | Connection from ('127.0.0.1', 56968) | waiting authorize
2022-11-30 11:48:22,914 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669798102.900856, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 11:48:22,916 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:48:22,918 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 11:48:25,281 |    INFO | server | Client ('127.0.0.1', 56968) wants to quit
2022-11-30 11:48:25,789 |    INFO | server | User "u2" disconnected
2022-11-30 11:48:31,284 | WARNING | server | Server closing
2022-11-30 11:48:46,860 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 11:48:46,865 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 11:48:48,662 | WARNING | server | Server closing
2022-11-30 12:03:00,823 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 12:03:00,826 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:03:03,558 | WARNING | server | Server closing
2022-11-30 12:04:45,332 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 21 | 
2022-11-30 12:04:45,336 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:04:46,747 | WARNING | server | Server closing
2022-11-30 12:05:39,910 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:05:39,915 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:05:45,102 | WARNING | server | Server closing
2022-11-30 12:07:23,343 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:07:23,347 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:07:28,595 |    INFO | server | Connection from ('127.0.0.1', 58064) | waiting authorize
2022-11-30 12:07:28,599 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799248.595521, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:07:28,602 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:07:28,604 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:07:41,431 |    INFO | server | Client ('127.0.0.1', 58064) wants to quit
2022-11-30 12:07:41,947 |    INFO | server | User "u2" disconnected
2022-11-30 12:07:49,226 | WARNING | server | Server closing
2022-11-30 12:13:05,671 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:13:05,674 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:15:20,287 |    INFO | server | Connection from ('127.0.0.1', 58371) | waiting authorize
2022-11-30 12:15:20,290 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799720.286005, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:15:20,292 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:15:20,294 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:15:29,491 |    INFO | server | Connection from ('127.0.0.1', 58379) | waiting authorize
2022-11-30 12:15:29,493 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799729.490784, 'user': {'password': 'password', 'username': 'u2'}}, {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AE2378BF70>()]> transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:15:29,493 |    INFO | server | User is already authorized
authorized = {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AE2378BF70>()]> transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}
2022-11-30 12:15:29,495 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:16:06,043 |    INFO | server | Client ('127.0.0.1', 58371) wants to quit
2022-11-30 12:16:06,556 |    INFO | server | User "u2" disconnected
2022-11-30 12:16:10,776 |    INFO | server | Client ('127.0.0.1', 58379) wants to quit
2022-11-30 12:16:11,291 |    INFO | server | User "u2" disconnected
2022-11-30 12:16:11,291 |   ERROR | server | Server error | u2 ('127.0.0.1', 58379) has already left
2022-11-30 12:17:11,271 |    INFO | server | Connection from ('127.0.0.1', 58461) | waiting authorize
2022-11-30 12:17:11,273 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799831.271336, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:17:11,275 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:17:11,277 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:17:36,394 |    INFO | server | User "u2" disconnected
2022-11-30 12:17:37,778 |    INFO | server | Connection from ('127.0.0.1', 58484) | waiting authorize
2022-11-30 12:17:37,780 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799857.778999, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:17:37,782 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:17:37,783 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:17:54,789 |    INFO | server | Client ('127.0.0.1', 58484) wants to quit
2022-11-30 12:17:55,292 |    INFO | server | User "u2" disconnected
2022-11-30 12:19:28,265 |    INFO | server | Connection from ('127.0.0.1', 58546) | waiting authorize
2022-11-30 12:19:28,267 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799968.265088, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:19:28,269 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:19:28,271 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:19:31,104 |    INFO | server | Client ('127.0.0.1', 58546) wants to quit
2022-11-30 12:19:31,617 |    INFO | server | User "u2" disconnected
2022-11-30 12:19:58,829 |    INFO | server | Connection from ('127.0.0.1', 58578) | waiting authorize
2022-11-30 12:19:58,831 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799998.829102, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:19:58,833 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:19:58,834 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:20:01,391 |    INFO | server | Client ('127.0.0.1', 58578) wants to quit
2022-11-30 12:20:01,898 |    INFO | server | User "u2" disconnected
2022-12-05 14:42:40,675 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:42:40,699 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:43:03,930 | WARNING | server | Server closing
2022-12-05 14:47:20,979 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:47:21,004 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:47:24,611 |    INFO | server | Connection from ('127.0.0.1', 65412) | waiting authorize
2022-12-05 14:47:24,617 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670240844.611519, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:47:24,619 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:47:24,620 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:49:38,632 | WARNING | server | Server closing
2022-12-05 14:51:40,810 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:53:02,322 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:54:31,582 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:55:40,589 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:55:40,609 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:55:46,004 |    INFO | server | Connection from ('127.0.0.1', 1222) | waiting authorize
2022-12-05 14:55:46,008 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241346.004928, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:55:46,009 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:55:46,011 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:56:09,853 |    INFO | server | Client ('127.0.0.1', 1222) wants to quit
2022-12-05 14:56:10,117 |    INFO | server | User "u2" disconnected
2022-12-05 14:56:17,413 |    INFO | server | Connection from ('127.0.0.1', 1239) | waiting authorize
2022-12-05 14:56:17,415 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241377.413395, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:56:17,417 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:56:17,419 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:57:37,754 | WARNING | server | Server closing
2022-12-05 14:57:39,522 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 14:57:39,542 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 14:57:46,394 |    INFO | server | Connection from ('127.0.0.1', 1295) | waiting authorize
2022-12-05 14:57:46,397 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241466.393858, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:57:46,398 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:57:46,400 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:57:54,656 |    INFO | server | Client ('127.0.0.1', 1295) wants to quit
2022-12-05 14:57:54,915 |    INFO | server | User "u2" disconnected
2022-12-05 14:58:00,560 |    INFO | server | Connection from ('127.0.0.1', 1305) | waiting authorize
2022-12-05 14:58:00,562 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241480.560387, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:58:00,564 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 14:58:00,565 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:59:14,661 |    INFO | server | Connection from ('127.0.0.1', 1351) | waiting authorize
2022-12-05 14:59:14,663 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670241554.661439, 'user': {'password': 'password', 'username': 'u2'}}, {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000023632660460>()]> transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 14:59:14,664 |    INFO | server | User is already authorized
authorized = {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000023632660460>()]> transport=<_ProactorSocketTransport fd=448 read=<_OverlappedFuture pending overlapped=<pending, 0x23632652dc0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}
2022-12-05 14:59:14,665 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 14:59:23,051 |    INFO | server | Client ('127.0.0.1', 1351) wants to quit
2022-12-05 14:59:23,304 |    INFO | server | User "u2" disconnected
2022-12-05 14:59:30,305 |    INFO | server | User "u2" disconnected
2022-12-05 14:59:30,305 |   ERROR | server | Server error | u2 ('127.0.0.1', 1305) has already left
2022-12-05 15:01:35,145 | WARNING | server | Server closing
2022-12-05 15:08:01,380 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:08:01,401 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:08:16,799 | WARNING | server | Server closing
2022-12-05 15:09:30,336 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:09:30,357 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:10:25,442 | WARNING | server | Server closing
2022-12-05 15:10:27,310 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:10:27,330 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:12:09,345 | WARNING | server | Server closing
2022-12-05 15:12:10,995 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:12:11,016 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:12:26,330 | WARNING | server | Server closing
2022-12-05 15:15:14,513 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:15:14,541 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:15:21,894 |    INFO | server | Connection from ('127.0.0.1', 1635) | waiting authorize
2022-12-05 15:15:21,897 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242521.888626, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:15:21,899 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:15:21,901 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:15:40,390 | WARNING | server | Server closing
2022-12-05 15:16:13,403 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:16:13,422 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:16:49,609 | WARNING | server | Server closing
2022-12-05 15:16:50,962 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:16:50,983 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:16:54,390 |    INFO | server | Connection from ('127.0.0.1', 1698) | waiting authorize
2022-12-05 15:16:54,393 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242614.383011, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:16:54,395 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:16:54,396 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:17:21,351 | WARNING | server | Server closing
2022-12-05 15:17:23,008 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:17:23,029 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:17:35,056 | WARNING | server | Server closing
2022-12-05 15:17:42,198 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:17:42,219 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:17:44,310 |    INFO | server | Connection from ('127.0.0.1', 1733) | waiting authorize
2022-12-05 15:17:44,314 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242664.303402, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:17:44,315 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:17:44,317 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:18:01,952 | WARNING | server | Server closing
2022-12-05 15:18:03,250 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:18:03,270 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:18:09,004 |    INFO | server | Connection from ('127.0.0.1', 1748) | waiting authorize
2022-12-05 15:18:09,007 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242688.997396, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:18:09,009 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:18:09,010 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:18:44,220 | WARNING | server | Server closing
2022-12-05 15:18:45,899 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:18:45,919 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:18:48,397 |    INFO | server | Connection from ('127.0.0.1', 1782) | waiting authorize
2022-12-05 15:18:48,400 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242728.394001, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:18:48,402 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:18:48,403 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:19:04,991 | WARNING | server | Server closing
2022-12-05 15:19:06,884 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:19:06,904 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:19:10,300 |    INFO | server | Connection from ('127.0.0.1', 1796) | waiting authorize
2022-12-05 15:19:10,303 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242750.297165, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:19:10,305 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:19:10,307 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:19:15,712 |    INFO | server | Client ('127.0.0.1', 1796) wants to quit
2022-12-05 15:19:15,964 |    INFO | server | User "u2" disconnected
2022-12-05 15:19:18,149 | WARNING | server | Server closing
2022-12-05 15:19:28,240 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:19:28,260 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:19:53,105 | WARNING | server | Server closing
2022-12-05 15:20:29,825 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:20:29,849 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:20:31,424 |    INFO | server | Connection from ('127.0.0.1', 1849) | waiting authorize
2022-12-05 15:20:31,427 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242831.421376, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:20:31,428 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:20:31,430 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:20:39,015 |    INFO | server | User "u2" disconnected
2022-12-05 15:20:41,065 | WARNING | server | Server closing
2022-12-05 15:20:42,074 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:20:42,094 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:20:43,211 |    INFO | server | Connection from ('127.0.0.1', 1865) | waiting authorize
2022-12-05 15:20:43,214 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242843.208664, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:20:43,216 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:20:43,218 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:21:41,627 |    INFO | server | User "u2" disconnected
2022-12-05 15:21:43,210 | WARNING | server | Server closing
2022-12-05 15:21:45,687 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:21:45,708 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:21:47,815 |    INFO | server | Connection from ('127.0.0.1', 1912) | waiting authorize
2022-12-05 15:21:47,819 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242907.808296, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:21:47,820 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:21:47,822 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:21:50,188 |    INFO | server | User "u2" disconnected
2022-12-05 15:22:31,162 | WARNING | server | Server closing
2022-12-05 15:22:32,229 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:22:32,251 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:22:34,587 |    INFO | server | Connection from ('127.0.0.1', 1937) | waiting authorize
2022-12-05 15:22:34,590 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242954.584696, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:22:34,592 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:22:34,594 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:22:49,362 | WARNING | server | Server closing
2022-12-05 15:22:53,242 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:22:53,302 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:22:58,715 |    INFO | server | Connection from ('127.0.0.1', 1969) | waiting authorize
2022-12-05 15:22:58,721 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670242978.710362, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:22:58,725 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:22:58,728 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:23:20,105 |    INFO | server | Client ('127.0.0.1', 1969) wants to quit
2022-12-05 15:23:20,356 |    INFO | server | User "u2" disconnected
2022-12-05 15:23:30,925 | WARNING | server | Server closing
2022-12-05 15:23:33,987 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:23:34,040 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:25:32,081 | WARNING | server | Server closing
2022-12-05 15:25:42,678 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:25:42,697 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:26:03,315 | WARNING | server | Server closing
2022-12-05 15:26:04,514 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:26:04,542 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:26:05,884 |    INFO | server | Connection from ('127.0.0.1', 2079) | waiting authorize
2022-12-05 15:26:05,887 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243165.881271, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:26:05,889 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:26:05,890 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:26:13,915 | WARNING | server | Server closing
2022-12-05 15:26:15,110 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:26:15,131 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:26:52,966 | WARNING | server | Server closing
2022-12-05 15:26:54,198 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:26:54,218 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:27:28,361 | WARNING | server | Server closing
2022-12-05 15:27:29,301 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:27:29,322 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:27:30,778 |    INFO | server | Connection from ('127.0.0.1', 2138) | waiting authorize
2022-12-05 15:27:30,781 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243250.775881, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:27:30,783 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:27:30,785 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:30:30,081 | WARNING | server | Server closing
2022-12-05 15:30:31,455 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:30:31,486 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:30:33,224 |    INFO | server | Connection from ('127.0.0.1', 2243) | waiting authorize
2022-12-05 15:30:33,227 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243433.22001, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:30:33,229 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:30:33,231 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:30:51,524 | WARNING | server | Server closing
2022-12-05 15:30:52,790 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:30:52,811 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:30:53,861 |    INFO | server | Connection from ('127.0.0.1', 2271) | waiting authorize
2022-12-05 15:30:53,864 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243453.858207, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:30:53,866 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:30:53,867 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:31:19,415 | WARNING | server | Server closing
2022-12-05 15:31:22,067 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:31:22,109 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:32:50,570 | WARNING | server | Server closing
2022-12-05 15:33:15,944 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:33:15,988 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:33:16,704 |    INFO | server | Connection from ('127.0.0.1', 2353) | waiting authorize
2022-12-05 15:33:16,708 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243596.701407, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:33:16,710 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:33:16,711 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:33:25,024 |    INFO | server | Client ('127.0.0.1', 2353) wants to quit
2022-12-05 15:33:25,285 |    INFO | server | User "u2" disconnected
2022-12-05 15:33:26,752 |    INFO | server | Connection from ('127.0.0.1', 2361) | waiting authorize
2022-12-05 15:33:26,754 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243606.750165, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:33:26,756 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:33:26,757 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:33:36,578 | WARNING | server | Server closing
2022-12-05 15:33:37,880 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:33:37,908 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:33:38,167 |    INFO | server | Connection from ('127.0.0.1', 2379) | waiting authorize
2022-12-05 15:33:38,170 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243618.164143, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:33:38,172 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:33:38,174 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:34:07,234 | WARNING | server | Server closing
2022-12-05 15:34:08,619 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:34:08,640 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:34:10,133 |    INFO | server | Connection from ('127.0.0.1', 2397) | waiting authorize
2022-12-05 15:34:10,136 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243650.127309, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:34:10,138 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:34:10,140 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:34:14,448 |    INFO | server | User "u2" disconnected
2022-12-05 15:34:55,669 | WARNING | server | Server closing
2022-12-05 15:35:00,146 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:35:00,166 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:36:08,303 | WARNING | server | Server closing
2022-12-05 15:36:13,138 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:36:13,158 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:37:22,541 | WARNING | server | Server closing
2022-12-05 15:37:23,586 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:37:23,607 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:37:26,082 |    INFO | server | Connection from ('127.0.0.1', 2523) | waiting authorize
2022-12-05 15:37:26,085 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243846.075762, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:37:26,087 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:37:26,089 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:37:29,262 |    INFO | server | User "u2" disconnected
2022-12-05 15:37:30,513 |    INFO | server | Connection from ('127.0.0.1', 2529) | waiting authorize
2022-12-05 15:37:30,515 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243850.506656, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:37:30,517 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:37:30,519 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:38:13,112 |    INFO | server | User "u2" disconnected
2022-12-05 15:38:15,013 |    INFO | server | Connection from ('127.0.0.1', 2569) | waiting authorize
2022-12-05 15:38:15,015 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670243895.007702, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 15:38:15,016 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-12-05 15:38:15,018 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 15:38:16,258 |    INFO | server | Client ('127.0.0.1', 2569) wants to quit
2022-12-05 15:38:16,518 |    INFO | server | User "u2" disconnected
2022-12-05 15:38:20,289 | WARNING | server | Server closing
2022-12-05 15:39:18,634 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:39:18,659 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:44:37,521 | WARNING | server | Server closing
2022-12-05 15:44:39,429 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:44:39,459 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:45:56,822 | WARNING | server | Server closing
2022-12-05 15:46:29,219 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:46:29,253 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:47:43,234 | WARNING | server | Server closing
2022-12-05 15:47:46,405 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:47:46,440 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:48:34,512 | WARNING | server | Server closing
2022-12-05 15:51:07,497 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:51:07,547 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:51:29,845 | WARNING | server | Server closing
2022-12-05 15:51:37,167 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:51:37,203 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:55:07,540 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:56:16,901 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 15:56:16,993 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:56:19,415 | WARNING | server | Server closing
2022-12-05 15:56:26,306 | WARNING | server | Server closing
2022-12-05 15:56:28,756 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:56:28,797 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:56:50,958 | WARNING | server | Server closing
2022-12-05 15:57:25,337 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:57:25,376 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:57:48,704 | WARNING | server | Server closing
2022-12-05 15:57:49,721 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:57:49,767 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:57:56,693 |    INFO | server | Connection from ('127.0.0.1', 3446) | waiting authorize
2022-12-05 15:57:56,696 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245076.687195, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 15:57:56,697 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 15:57:56,699 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 15:59:04,868 | WARNING | server | Server closing
2022-12-05 15:59:06,041 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:59:06,076 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:59:30,086 |    INFO | server | Connection from ('127.0.0.1', 3524) | waiting authorize
2022-12-05 15:59:30,090 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245170.079151, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 15:59:30,092 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 15:59:30,094 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 15:59:52,557 | WARNING | server | Server closing
2022-12-05 15:59:53,620 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 15:59:53,655 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 15:59:55,956 |    INFO | server | Connection from ('127.0.0.1', 12098) | waiting authorize
2022-12-05 15:59:55,959 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245195.950978, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 15:59:55,961 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 15:59:55,962 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:00:24,838 |    INFO | server | User "u2" disconnected
2022-12-05 16:01:20,283 | WARNING | server | Server closing
2022-12-05 16:01:21,438 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:01:21,475 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:01:48,082 | WARNING | server | Server closing
2022-12-05 16:01:48,893 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:01:48,928 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:02:55,955 | WARNING | server | Server closing
2022-12-05 16:02:57,238 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:02:57,276 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:02:59,842 |    INFO | server | Connection from ('127.0.0.1', 12212) | waiting authorize
2022-12-05 16:02:59,846 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245379.836768, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:02:59,848 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:02:59,850 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:03:06,379 |    INFO | server | User "u2" disconnected
2022-12-05 16:03:08,221 |    INFO | server | Connection from ('127.0.0.1', 12220) | waiting authorize
2022-12-05 16:03:08,223 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245388.216102, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:03:08,225 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:03:08,226 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:03:17,992 |    INFO | server | Client ('127.0.0.1', 12220) wants to quit
2022-12-05 16:03:18,250 |    INFO | server | User "u2" disconnected
2022-12-05 16:03:20,827 | WARNING | server | Server closing
2022-12-05 16:04:07,159 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 16:04:07,212 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:04:26,371 |    INFO | server | Connection from ('127.0.0.1', 39304) | waiting authorize
2022-12-05 16:04:26,383 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245466.356406, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 59 | 
2022-12-05 16:04:26,394 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 139 | 
2022-12-05 16:04:26,400 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 60 | 
2022-12-05 16:04:45,389 |    INFO | server | Client ('127.0.0.1', 39304) wants to quit
2022-12-05 16:04:45,640 |    INFO | server | User "u2" disconnected
2022-12-05 16:04:46,962 |    INFO | server | Connection from ('127.0.0.1', 39306) | waiting authorize
2022-12-05 16:04:46,968 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245486.948171, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 59 | 
2022-12-05 16:04:46,979 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 139 | 
2022-12-05 16:04:46,986 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 60 | 
2022-12-05 16:04:53,721 | WARNING | server | Server closing
2022-12-05 16:10:35,302 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:10:57,902 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:10:57,942 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:11:11,408 |    INFO | server | Connection from ('127.0.0.1', 12508) | waiting authorize
2022-12-05 16:11:11,411 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245871.403694, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:11:11,413 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:11:11,415 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:11:34,894 | WARNING | server | Server closing
2022-12-05 16:13:14,305 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:13:14,344 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:13:16,823 |    INFO | server | Connection from ('127.0.0.1', 12580) | waiting authorize
2022-12-05 16:13:16,827 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670245996.822798, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:13:16,828 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:13:16,830 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:14:17,237 | WARNING | server | Server closing
2022-12-05 16:14:21,068 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:14:21,129 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:14:23,426 |    INFO | server | Connection from ('127.0.0.1', 12619) | waiting authorize
2022-12-05 16:14:23,430 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246063.425157, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 16:14:23,432 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 139 | 
2022-12-05 16:14:23,433 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 16:21:58,144 | WARNING | server | Server closing
2022-12-05 16:22:00,361 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:22:00,401 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:22:03,200 |    INFO | server | Connection from ('127.0.0.1', 13008) | waiting authorize
2022-12-05 16:22:03,204 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246523.200436, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:22:03,205 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 144 | 
2022-12-05 16:22:03,207 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:22:10,088 | WARNING | server | Server closing
2022-12-05 16:27:26,587 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:27:26,625 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:27:29,594 |    INFO | server | Connection from ('127.0.0.1', 13286) | waiting authorize
2022-12-05 16:27:29,597 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246849.594825, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:27:29,600 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:27:32,197 |    INFO | server | Client ('127.0.0.1', 13286) wants to quit
2022-12-05 16:27:32,455 |    INFO | server | User "u2" disconnected
2022-12-05 16:27:32,455 |   ERROR | server | Server error | u2 ('127.0.0.1', 13286) has already left
2022-12-05 16:27:58,527 | WARNING | server | Server closing
2022-12-05 16:28:01,026 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:28:01,062 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:28:03,536 |    INFO | server | Connection from ('127.0.0.1', 13310) | waiting authorize
2022-12-05 16:28:03,539 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670246883.534081, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:28:03,541 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:28:03,542 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:28:07,268 |    INFO | server | Client ('127.0.0.1', 13310) wants to quit
2022-12-05 16:28:07,527 |    INFO | server | User "u2" disconnected
2022-12-05 16:28:10,537 | WARNING | server | Server closing
2022-12-05 16:34:06,153 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:34:06,193 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:34:10,047 |    INFO | server | Connection from ('127.0.0.1', 13561) | waiting authorize
2022-12-05 16:34:10,050 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670247250.046162, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:34:10,052 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:34:17,451 | WARNING | server | Server closing
2022-12-05 16:34:27,442 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:34:27,487 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:34:30,486 |    INFO | server | Connection from ('127.0.0.1', 13574) | waiting authorize
2022-12-05 16:34:30,489 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670247270.485513, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:34:30,491 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:34:47,423 | WARNING | server | Server closing
2022-12-05 16:34:49,696 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:34:49,767 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:34:52,432 |    INFO | server | Connection from ('127.0.0.1', 13592) | waiting authorize
2022-12-05 16:34:52,435 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670247292.431233, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:34:52,437 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:34:52,440 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:34:57,846 |    INFO | server | Client ('127.0.0.1', 13592) wants to quit
2022-12-05 16:34:58,111 |    INFO | server | User "u2" disconnected
2022-12-05 16:45:32,812 | WARNING | server | Server closing
2022-12-05 16:45:34,556 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:45:34,600 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:45:38,123 |    INFO | server | Connection from ('127.0.0.1', 14359) | waiting authorize
2022-12-05 16:45:38,126 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670247938.12211, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:45:38,128 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:46:01,324 | WARNING | server | Server closing
2022-12-05 16:46:04,079 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:46:04,120 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:46:07,392 |    INFO | server | Connection from ('127.0.0.1', 14375) | waiting authorize
2022-12-05 16:46:07,396 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670247967.391124, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:46:07,399 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:46:07,402 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 58 | 
2022-12-05 16:47:57,280 |    INFO | server | Client ('127.0.0.1', 14375) wants to quit
2022-12-05 16:47:57,539 |    INFO | server | User "u2" disconnected
2022-12-05 16:48:01,007 | WARNING | server | Server closing
2022-12-05 16:49:07,787 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:49:07,825 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:49:27,820 | WARNING | server | Server closing
2022-12-05 16:49:30,410 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:49:30,446 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:49:36,457 | WARNING | server | Server closing
2022-12-05 16:49:38,328 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:49:38,363 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:49:45,005 | WARNING | server | Server closing
2022-12-05 16:49:58,348 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:49:58,384 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:50:01,185 |    INFO | server | Connection from ('127.0.0.1', 14662) | waiting authorize
2022-12-05 16:50:03,910 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248203.906402, 'user': {'password': 'pas', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:50:03,912 |    INFO | server | fnc: make_secure_password | args: ('pas',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:50:08,174 | WARNING | server | Server closing
2022-12-05 16:50:39,439 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:50:39,476 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:50:41,962 |    INFO | server | Connection from ('127.0.0.1', 14694) | waiting authorize
2022-12-05 16:50:44,311 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248244.307859, 'user': {'password': 'asd', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:50:44,313 |    INFO | server | fnc: make_secure_password | args: ('asd',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:51:35,377 | WARNING | server | Server closing
2022-12-05 16:51:38,198 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:51:38,232 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:51:41,459 |    INFO | server | Connection from ('127.0.0.1', 14753) | waiting authorize
2022-12-05 16:51:44,493 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248304.489754, 'user': {'password': 'asd', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:51:44,495 |    INFO | server | fnc: make_secure_password | args: ('asd',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:51:44,497 | WARNING | server | Wrong password for: u2
2022-12-05 16:51:44,497 | WARNING | server | User cant get authorized
2022-12-05 16:51:44,499 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 16:51:50,295 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248310.293544, 'user': {'password': 'asd', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 16:51:50,297 |    INFO | server | fnc: make_secure_password | args: ('asd',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 146 | 
2022-12-05 16:51:50,298 | WARNING | server | Wrong password for: u2
2022-12-05 16:51:50,299 | WARNING | server | User cant get authorized
2022-12-05 16:51:50,300 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 16:53:17,536 | WARNING | server | Server closing
2022-12-05 16:54:04,397 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 16:54:04,452 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:54:13,336 |    INFO | server | Connection from ('127.0.0.1', 39312) | waiting authorize
2022-12-05 16:54:15,104 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248455.093849, 'user': {'password': 'asd', 'username': 'u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 56 | 
2022-12-05 16:54:15,116 |    INFO | server | fnc: make_secure_password | args: ('asd',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 145 | 
2022-12-05 16:54:15,118 | WARNING | server | Wrong password for: u2
2022-12-05 16:54:15,119 | WARNING | server | User cant get authorized
2022-12-05 16:54:15,126 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 71 | 
2022-12-05 16:54:17,630 |    INFO | server | ('127.0.0.1', 39312) has disconnected without authorization
2022-12-05 16:54:35,081 | WARNING | server | Server closing
2022-12-05 16:55:01,980 |    INFO | server | fnc: get_database_object | args: (PosixPath('/mnt/i/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/server.py | Called from function <module> line 24 | 
2022-12-05 16:55:02,032 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:55:06,956 |    INFO | server | Connection from ('127.0.0.1', 39314) | waiting authorize
2022-12-05 16:55:08,851 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248508.844177, 'user': {'password': 'asd', 'username': 'u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 56 | 
2022-12-05 16:55:08,860 |    INFO | server | fnc: make_secure_password | args: ('asd',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 145 | 
2022-12-05 16:55:08,862 | WARNING | server | Wrong password for: u2
2022-12-05 16:55:08,862 | WARNING | server | User cant get authorized
2022-12-05 16:55:08,867 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 71 | 
2022-12-05 16:55:17,526 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248517.520246, 'user': {'password': 'ss', 'username': '/register u2'}}, {}) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 56 | 
2022-12-05 16:55:17,534 |    INFO | server | fnc: make_secure_password | args: ('ss',) | kwargs: {} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function verify_password line 145 | 
2022-12-05 16:55:17,536 | WARNING | server | Wrong password for: /register u2
2022-12-05 16:55:17,536 | WARNING | server | User cant get authorized
2022-12-05 16:55:17,542 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: /mnt/i/docker_practice/gb_client_server_apps/project/utils/utils.py | Called from function handle_request line 71 | 
2022-12-05 16:55:32,343 | WARNING | server | Server closing
2022-12-05 16:55:50,629 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 16:55:50,690 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 16:55:53,368 |    INFO | server | Connection from ('127.0.0.1', 14907) | waiting authorize
2022-12-05 16:56:02,612 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670248562.607467, 'user': {'password': 'asd', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 16:56:02,614 |    INFO | server | fnc: make_secure_password | args: ('asd',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 145 | 
2022-12-05 16:56:02,615 | WARNING | server | Wrong password for: u2
2022-12-05 16:56:02,616 | WARNING | server | User cant get authorized
2022-12-05 16:56:02,617 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-05 16:56:07,086 |    INFO | server | ('127.0.0.1', 14907) has disconnected without authorization
2022-12-05 16:57:09,475 |    INFO | server | Connection from ('127.0.0.1', 14942) | waiting authorize
2022-12-05 16:57:11,923 |    INFO | server | ('127.0.0.1', 14942) has disconnected without authorization
2022-12-05 17:06:46,924 |    INFO | server | Connection from ('127.0.0.1', 15282) | waiting authorize
2022-12-05 17:07:03,010 |    INFO | server | ('127.0.0.1', 15282) has disconnected without authorization
2022-12-05 17:07:04,845 |    INFO | server | Connection from ('127.0.0.1', 15291) | waiting authorize
2022-12-05 17:07:37,126 | WARNING | server | Server closing
2022-12-05 17:11:24,254 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:11:24,298 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:11:28,459 |    INFO | server | Connection from ('127.0.0.1', 15434) | waiting authorize
2022-12-05 17:11:49,276 |    INFO | server | ('127.0.0.1', 15434) has disconnected without authorization
2022-12-05 17:13:47,283 |    INFO | server | Connection from ('127.0.0.1', 15516) | waiting authorize
2022-12-05 17:13:49,268 | WARNING | server | Server closing
2022-12-05 17:13:52,514 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:13:52,548 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:13:55,195 |    INFO | server | Connection from ('127.0.0.1', 15531) | waiting authorize
2022-12-05 17:14:01,010 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 55 | 
2022-12-05 17:14:01,265 |    INFO | server | ('127.0.0.1', 15531) has disconnected without authorization
2022-12-05 17:15:53,785 |    INFO | server | Connection from ('127.0.0.1', 15598) | waiting authorize
2022-12-05 17:16:00,048 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 55 | 
2022-12-05 17:16:00,303 |    INFO | server | ('127.0.0.1', 15598) has disconnected without authorization
2022-12-05 17:18:09,861 |    INFO | server | Connection from ('127.0.0.1', 15678) | waiting authorize
2022-12-05 17:18:16,916 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 55 | 
2022-12-05 17:19:50,656 | WARNING | server | Server closing
2022-12-05 17:19:53,081 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:19:53,118 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:19:55,371 |    INFO | server | Connection from ('127.0.0.1', 15744) | waiting authorize
2022-12-05 17:20:00,109 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 55 | 
2022-12-05 17:20:07,113 | WARNING | server | Server closing
2022-12-05 17:26:12,220 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:26:12,255 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:26:14,796 |    INFO | server | Connection from ('127.0.0.1', 15965) | waiting authorize
2022-12-05 17:29:06,731 | WARNING | server | Server closing
2022-12-05 17:29:10,125 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:29:10,164 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:29:12,492 |    INFO | server | Connection from ('127.0.0.1', 16057) | waiting authorize
2022-12-05 17:29:19,880 |    INFO | server | ('127.0.0.1', 16057) has disconnected without authorization
2022-12-05 17:31:38,227 |    INFO | server | Connection from ('127.0.0.1', 16150) | waiting authorize
2022-12-05 17:31:53,093 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670250713.088395, 'user': {'password': 'pass', 'username': ' Gerasim'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 63 | 
2022-12-05 17:31:53,096 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 152 | 
2022-12-05 17:31:53,097 | WARNING | server | Wrong password for:  Gerasim
2022-12-05 17:31:53,098 | WARNING | server | User cant get authorized
2022-12-05 17:31:53,099 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 78 | 
2022-12-05 17:33:28,450 |    INFO | server | ('127.0.0.1', 16150) has disconnected without authorization
2022-12-05 17:33:31,467 |    INFO | server | Connection from ('127.0.0.1', 16208) | waiting authorize
2022-12-05 17:33:59,082 | WARNING | server | Server closing
2022-12-05 17:34:01,274 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:34:01,320 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:34:03,557 |    INFO | server | Connection from ('127.0.0.1', 16234) | waiting authorize
2022-12-05 17:34:11,048 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 234 | 
2022-12-05 17:34:11,051 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:34:51,234 | WARNING | server | Server closing
2022-12-05 17:36:12,293 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:36:12,326 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:36:14,795 |    INFO | server | Connection from ('127.0.0.1', 16319) | waiting authorize
2022-12-05 17:36:23,952 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 235 | 
2022-12-05 17:36:23,955 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:37:05,177 | WARNING | server | Server closing
2022-12-05 17:37:08,256 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:37:08,290 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:37:10,499 |    INFO | server | Connection from ('127.0.0.1', 16357) | waiting authorize
2022-12-05 17:37:19,279 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670251039.275356, 'user': {'password': '/register Vass', 'username': ''}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 63 | 
2022-12-05 17:37:19,279 | WARNING | server | Wrong password for: 
2022-12-05 17:37:19,280 | WARNING | server | User cant get authorized
2022-12-05 17:37:19,282 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 78 | 
2022-12-05 17:37:50,783 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 235 | 
2022-12-05 17:37:50,789 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:38:06,567 |    INFO | server | ('127.0.0.1', 16357) has disconnected without authorization
2022-12-05 17:38:43,348 |    INFO | server | Connection from ('127.0.0.1', 16414) | waiting authorize
2022-12-05 17:38:51,553 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 235 | 
2022-12-05 17:40:20,563 | WARNING | server | Server closing
2022-12-05 17:40:33,714 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:40:33,752 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:40:36,181 |    INFO | server | Connection from ('127.0.0.1', 16477) | waiting authorize
2022-12-05 17:40:46,805 |    INFO | server | fnc: make_secure_password | args: ('ps',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 237 | 
2022-12-05 17:40:46,811 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:41:03,175 |    INFO | server | Connection from ('127.0.0.1', 16499) | waiting authorize
2022-12-05 17:43:14,065 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 237 | 
2022-12-05 17:43:14,070 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:43:36,588 |    INFO | server | Connection from ('127.0.0.1', 16575) | waiting authorize
2022-12-05 17:43:41,902 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 237 | 
2022-12-05 17:43:41,908 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:45:09,367 | WARNING | server | Server closing
2022-12-05 17:45:12,842 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:45:12,880 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:45:15,169 |    INFO | server | Connection from ('127.0.0.1', 16639) | waiting authorize
2022-12-05 17:45:20,770 |    INFO | server | fnc: make_secure_password | args: ('pas',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 241 | 
2022-12-05 17:45:20,777 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:45:26,490 |    INFO | server | Connection from ('127.0.0.1', 16647) | waiting authorize
2022-12-05 17:45:38,163 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 241 | 
2022-12-05 17:45:38,169 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:48:45,447 | WARNING | server | Server closing
2022-12-05 17:48:56,034 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:48:56,072 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:48:59,075 |    INFO | server | Connection from ('127.0.0.1', 16770) | waiting authorize
2022-12-05 17:49:07,638 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 247 | 
2022-12-05 17:49:07,644 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 17:49:43,288 |    INFO | server | Client ('127.0.0.1', 16770) wants to quit
2022-12-05 17:49:43,540 |    INFO | server | ('127.0.0.1', 16770) has disconnected without authorization
2022-12-05 17:49:46,038 |    INFO | server | Connection from ('127.0.0.1', 16803) | waiting authorize
2022-12-05 17:49:51,713 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 247 | 
2022-12-05 17:49:51,719 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 17:50:02,988 |    INFO | server | Client ('127.0.0.1', 16803) wants to quit
2022-12-05 17:50:03,250 |    INFO | server | ('127.0.0.1', 16803) has disconnected without authorization
2022-12-05 17:50:04,478 |    INFO | server | Connection from ('127.0.0.1', 16824) | waiting authorize
2022-12-05 17:50:10,217 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'User already exists'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 17:51:24,189 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 247 | 
2022-12-05 17:51:24,195 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-12-05 17:54:16,197 | WARNING | server | Server closing
2022-12-05 17:54:29,692 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 17:54:29,729 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 17:54:32,389 |    INFO | server | Connection from ('127.0.0.1', 17001) | waiting authorize
2022-12-05 17:54:39,834 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 246 | 
2022-12-05 17:54:39,841 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 17:56:14,368 |    INFO | server | Client ('127.0.0.1', 17001) wants to quit
2022-12-05 17:56:14,620 |    INFO | server | ('127.0.0.1', 17001) has disconnected without authorization
2022-12-05 17:56:17,042 |    INFO | server | Connection from ('127.0.0.1', 17066) | waiting authorize
2022-12-05 17:56:21,180 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670252181.177852, 'user': {'password': 'pass', 'username': 'pass'}}, {'pass': <StreamWriter transport=<_ProactorSocketTransport closed> reader=<StreamReader eof transport=<_ProactorSocketTransport closed>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-12-05 17:56:21,180 |    INFO | server | User is already authorized
authorized = {'pass': <StreamWriter transport=<_ProactorSocketTransport closed> reader=<StreamReader eof transport=<_ProactorSocketTransport closed>>>}
2022-12-05 17:56:21,182 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 68 | 
2022-12-05 17:56:26,462 |    INFO | server | Client ('127.0.0.1', 17066) wants to quit
2022-12-05 17:56:26,716 |    INFO | server | User "pass" disconnected
2022-12-05 17:56:28,608 |    INFO | server | Connection from ('127.0.0.1', 17079) | waiting authorize
2022-12-05 17:56:33,916 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'User already exists'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 60 | 
2022-12-05 17:56:38,981 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670252198.979386, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-12-05 17:56:38,983 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 156 | 
2022-12-05 17:56:38,985 | WARNING | server | Wrong password for: pass
2022-12-05 17:56:38,985 | WARNING | server | User cant get authorized
2022-12-05 17:56:38,987 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 82 | 
2022-12-05 17:56:53,771 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670252213.769708, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-12-05 17:56:53,773 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 156 | 
2022-12-05 17:56:53,775 | WARNING | server | Wrong password for: pass
2022-12-05 17:56:53,775 | WARNING | server | User cant get authorized
2022-12-05 17:56:53,777 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 82 | 
2022-12-05 18:00:10,221 |    INFO | server | Client ('127.0.0.1', 17079) wants to quit
2022-12-05 18:00:10,486 |    INFO | server | ('127.0.0.1', 17079) has disconnected without authorization
2022-12-05 18:00:29,963 |    INFO | server | Connection from ('127.0.0.1', 17247) | waiting authorize
2022-12-05 18:00:38,760 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670252438.758539, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-12-05 18:00:38,762 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 156 | 
2022-12-05 18:00:38,764 | WARNING | server | Wrong password for: pass
2022-12-05 18:00:38,764 | WARNING | server | User cant get authorized
2022-12-05 18:00:38,766 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 82 | 
2022-12-05 18:18:18,599 | WARNING | server | Server closing
2022-12-05 18:18:27,011 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:18:27,048 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:18:29,920 |    INFO | server | Connection from ('127.0.0.1', 17969) | waiting authorize
2022-12-05 18:18:35,458 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 246 | 
2022-12-05 18:18:35,466 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 18:18:41,125 |    INFO | server | Client ('127.0.0.1', 17969) wants to quit
2022-12-05 18:18:41,381 |    INFO | server | ('127.0.0.1', 17969) has disconnected without authorization
2022-12-05 18:19:11,014 | WARNING | server | Server closing
2022-12-05 18:19:13,255 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:19:13,292 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:19:17,598 |    INFO | server | Connection from ('127.0.0.1', 18006) | waiting authorize
2022-12-05 18:19:23,242 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 246 | 
2022-12-05 18:19:23,249 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-12-05 18:19:29,595 |    INFO | server | Client ('127.0.0.1', 18006) wants to quit
2022-12-05 18:19:29,857 |    INFO | server | ('127.0.0.1', 18006) has disconnected without authorization
2022-12-05 18:19:32,998 |    INFO | server | Connection from ('127.0.0.1', 18017) | waiting authorize
2022-12-05 18:19:37,711 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670253577.709494, 'user': {'password': 'pass', 'username': 'pass'}}, {'pass': <StreamWriter transport=<_ProactorSocketTransport closed> reader=<StreamReader eof transport=<_ProactorSocketTransport closed>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-12-05 18:19:37,712 |    INFO | server | User is already authorized
authorized = {'pass': <StreamWriter transport=<_ProactorSocketTransport closed> reader=<StreamReader eof transport=<_ProactorSocketTransport closed>>>}
2022-12-05 18:19:37,713 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 68 | 
2022-12-05 18:19:40,072 |    INFO | server | Client ('127.0.0.1', 18017) wants to quit
2022-12-05 18:19:40,328 |    INFO | server | User "pass" disconnected
2022-12-05 18:21:42,270 |    INFO | server | Connection from ('127.0.0.1', 18115) | waiting authorize
2022-12-05 18:21:45,645 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670253705.641392, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 67 | 
2022-12-05 18:21:45,647 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 156 | 
2022-12-05 18:21:45,648 | WARNING | server | Wrong password for: pass
2022-12-05 18:21:45,649 | WARNING | server | User cant get authorized
2022-12-05 18:21:45,650 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 82 | 
2022-12-05 18:35:49,721 | WARNING | server | Server closing
2022-12-05 18:35:54,195 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:35:54,315 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:35:56,730 |    INFO | server | Connection from ('127.0.0.1', 18621) | waiting authorize
2022-12-05 18:35:59,663 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670254559.65992, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 69 | 
2022-12-05 18:35:59,665 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 158 | 
2022-12-05 18:35:59,667 | WARNING | server | Wrong password for: pass
2022-12-05 18:35:59,667 | WARNING | server | User cant get authorized
2022-12-05 18:35:59,669 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 84 | 
2022-12-05 18:36:09,278 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 248 | 
2022-12-05 18:36:09,284 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 18:36:27,653 | WARNING | server | Server closing
2022-12-05 18:39:22,105 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:39:22,143 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:39:28,116 |    INFO | server | Connection from ('127.0.0.1', 18743) | waiting authorize
2022-12-05 18:39:33,411 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 248 | 
2022-12-05 18:39:33,418 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 18:44:40,435 | WARNING | server | Server closing
2022-12-05 18:49:16,482 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:49:16,517 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:49:19,573 |    INFO | server | Connection from ('127.0.0.1', 19077) | waiting authorize
2022-12-05 18:49:27,911 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 248 | 
2022-12-05 18:49:27,917 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 18:51:50,492 | WARNING | server | Server closing
2022-12-05 18:51:55,036 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:51:55,077 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:51:58,179 |    INFO | server | Connection from ('127.0.0.1', 19214) | waiting authorize
2022-12-05 18:52:04,866 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 248 | 
2022-12-05 18:52:04,872 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 59 | 
2022-12-05 18:54:43,139 | WARNING | server | Server closing
2022-12-05 18:55:35,353 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 18:55:35,418 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 18:55:37,718 |    INFO | server | Connection from ('127.0.0.1', 19386) | waiting authorize
2022-12-05 18:55:45,223 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 250 | 
2022-12-05 18:55:45,230 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:02:49,671 | WARNING | server | Server closing
2022-12-05 19:02:51,104 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:02:51,144 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:02:54,262 |    INFO | server | Connection from ('127.0.0.1', 19645) | waiting authorize
2022-12-05 19:02:59,336 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 250 | 
2022-12-05 19:02:59,342 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:07:30,163 | WARNING | server | Server closing
2022-12-05 19:07:31,579 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:07:31,616 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:07:34,455 |    INFO | server | Connection from ('127.0.0.1', 19835) | waiting authorize
2022-12-05 19:07:39,761 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 251 | 
2022-12-05 19:07:39,768 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:07:46,048 |    INFO | server | Client ('127.0.0.1', 19835) wants to quit
2022-12-05 19:07:46,313 |    INFO | server | ('127.0.0.1', 19835) has disconnected without authorization
2022-12-05 19:08:59,456 |    INFO | server | Connection from ('127.0.0.1', 19885) | waiting authorize
2022-12-05 19:09:04,653 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670256544.650116, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:09:04,655 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:09:04,656 | WARNING | server | Wrong password for: pass
2022-12-05 19:09:04,657 | WARNING | server | User cant get authorized
2022-12-05 19:09:04,658 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 87 | 
2022-12-05 19:14:22,213 | WARNING | server | Server closing
2022-12-05 19:14:23,611 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:14:23,655 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:14:26,400 |    INFO | server | Connection from ('127.0.0.1', 20061) | waiting authorize
2022-12-05 19:14:29,454 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670256869.450889, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:14:29,456 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:14:29,459 | WARNING | server | Wrong password for: pass
2022-12-05 19:14:29,459 | WARNING | server | User cant get authorized
2022-12-05 19:14:29,461 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 87 | 
2022-12-05 19:14:37,199 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 252 | 
2022-12-05 19:14:37,206 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:14:39,850 |    INFO | server | Client ('127.0.0.1', 20061) wants to quit
2022-12-05 19:14:40,115 |    INFO | server | ('127.0.0.1', 20061) has disconnected without authorization
2022-12-05 19:14:41,571 |    INFO | server | Connection from ('127.0.0.1', 20078) | waiting authorize
2022-12-05 19:14:44,821 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670256884.818286, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:14:44,823 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:14:44,824 | WARNING | server | Wrong password for: pass
2022-12-05 19:14:44,824 | WARNING | server | User cant get authorized
2022-12-05 19:14:44,826 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 87 | 
2022-12-05 19:17:32,188 | WARNING | server | Server closing
2022-12-05 19:17:33,527 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:17:33,632 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:17:36,197 |    INFO | server | Connection from ('127.0.0.1', 20186) | waiting authorize
2022-12-05 19:17:40,972 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 19:17:40,979 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:17:43,178 |    INFO | server | Client ('127.0.0.1', 20186) wants to quit
2022-12-05 19:17:43,438 |    INFO | server | ('127.0.0.1', 20186) has disconnected without authorization
2022-12-05 19:17:45,051 |    INFO | server | Connection from ('127.0.0.1', 20200) | waiting authorize
2022-12-05 19:17:47,599 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670257067.596688, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:17:47,601 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:17:47,604 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 73 | 
2022-12-05 19:19:53,413 | WARNING | server | Server closing
2022-12-05 19:19:58,123 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:19:58,159 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:20:02,038 |    INFO | server | Connection from ('127.0.0.1', 20279) | waiting authorize
2022-12-05 19:20:06,473 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 19:20:06,480 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:20:08,071 |    INFO | server | Client ('127.0.0.1', 20279) wants to quit
2022-12-05 19:20:08,337 |    INFO | server | ('127.0.0.1', 20279) has disconnected without authorization
2022-12-05 19:20:19,049 |    INFO | server | Connection from ('127.0.0.1', 20290) | waiting authorize
2022-12-05 19:20:25,575 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670257225.573272, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:20:25,578 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:20:25,580 | WARNING | server | Wrong password for: pass
2022-12-05 19:20:25,580 | WARNING | server | User cant get authorized
2022-12-05 19:20:25,581 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 87 | 
2022-12-05 19:20:28,985 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670257228.983033, 'user': {'password': 'pass', 'username': 'vass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:20:28,987 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:20:28,990 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 73 | 
2022-12-05 19:20:33,631 |    INFO | server | Client ('127.0.0.1', 20290) wants to quit
2022-12-05 19:20:33,891 |    INFO | server | ('127.0.0.1', 20290) has disconnected without authorization
2022-12-05 19:20:51,789 |    INFO | server | Connection from ('127.0.0.1', 20317) | waiting authorize
2022-12-05 19:20:56,469 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670257256.465964, 'user': {'password': 'pass', 'username': 'vass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 19:20:56,469 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 19:20:56,474 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 73 | 
2022-12-05 19:21:46,886 | WARNING | server | Server closing
2022-12-05 19:21:47,902 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:21:47,999 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:21:50,440 |    INFO | server | Connection from ('127.0.0.1', 20369) | waiting authorize
2022-12-05 19:21:55,292 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 19:21:55,299 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:22:50,777 | WARNING | server | Server closing
2022-12-05 19:22:52,521 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:22:52,561 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:22:54,704 |    INFO | server | Connection from ('127.0.0.1', 20403) | waiting authorize
2022-12-05 19:23:00,212 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 19:23:00,218 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:23:37,865 | WARNING | server | Server closing
2022-12-05 19:23:39,605 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 19:23:39,645 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 19:23:46,707 |    INFO | server | Connection from ('127.0.0.1', 20441) | waiting authorize
2022-12-05 19:23:55,261 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 19:23:55,267 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'New user creation'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 19:24:01,853 |    INFO | server | Client ('127.0.0.1', 20441) wants to quit
2022-12-05 19:24:02,116 |    INFO | server | User "vass" disconnected
2022-12-05 19:24:02,116 |   ERROR | server | Server error | vass ('127.0.0.1', 20441) has already left
2022-12-05 19:24:05,943 | WARNING | server | Server closing
2022-12-05 20:53:27,973 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 20:53:28,083 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 20:53:30,142 |    INFO | server | Connection from ('127.0.0.1', 34373) | waiting authorize
2022-12-05 20:53:35,840 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 20:53:35,846 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 20:53:38,424 |    INFO | server | fnc: generate_response_message | args: (<Status.NotFound: 404>,) | kwargs: {'error': 'User is not logged in'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 101 | 
2022-12-05 20:53:38,676 |    INFO | server | ('127.0.0.1', 34373) has disconnected without authorization
2022-12-05 20:54:25,177 |    INFO | server | Connection from ('127.0.0.1', 34402) | waiting authorize
2022-12-05 20:54:29,093 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670262869.091005, 'user': {'password': 'pass', 'username': 'pass'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-05 20:54:29,096 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 161 | 
2022-12-05 20:54:29,099 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 20:54:47,795 |    INFO | server | Client ('127.0.0.1', 34402) wants to quit
2022-12-05 20:54:48,048 |    INFO | server | User "pass" disconnected
2022-12-05 20:54:48,048 |   ERROR | server | Server error | pass ('127.0.0.1', 34402) has already left
2022-12-05 20:54:52,762 | WARNING | server | Server closing
2022-12-05 20:55:06,982 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 20:55:07,027 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 20:55:09,384 |    INFO | server | Connection from ('127.0.0.1', 34432) | waiting authorize
2022-12-05 20:55:14,311 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670262914.306214, 'user': {'password': 'pasd', 'username': ''}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-05 20:55:14,312 | WARNING | server | Wrong password for: 
2022-12-05 20:55:14,312 | WARNING | server | User cant get authorized
2022-12-05 20:55:14,314 |    INFO | server | fnc: generate_response_message | args: (<Status.NotAuthorized: 401>,) | kwargs: {'error': 'Wrong user or password'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 86 | 
2022-12-05 20:55:21,789 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 253 | 
2022-12-05 20:55:21,796 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 22:14:54,819 | WARNING | server | Server closing
2022-12-05 22:25:50,862 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 24 | 
2022-12-05 22:25:50,903 |    INFO | server | Listening at 127.0.0.1:4444
2022-12-05 22:25:53,448 |    INFO | server | Connection from ('127.0.0.1', 37430) | waiting authorize
2022-12-05 22:25:59,868 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function create_new_user line 256 | 
2022-12-05 22:25:59,874 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Created'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 61 | 
2022-12-05 22:26:04,995 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1670268364.993076, 'user': {'password': 'pass', 'username': 'Vasya'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 71 | 
2022-12-05 22:26:04,998 |    INFO | server | fnc: make_secure_password | args: ('pass',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 164 | 
2022-12-05 22:26:05,001 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 72 | 
2022-12-05 22:26:07,505 |    INFO | server | Client ('127.0.0.1', 37430) wants to quit
2022-12-05 22:26:07,766 |    INFO | server | User "Vasya" disconnected
2022-12-05 22:26:07,766 |   ERROR | server | Server error | Vasya ('127.0.0.1', 37430) has already left
2022-12-05 22:26:13,102 | WARNING | server | Server closing
